---
title: "Metadata fields"
format: html
---

Attributes for range shifts data:
* Polygon.Name: Name of Polygon
    * Each study area has a unique polygon title. Polygon title was generated by concatenating the PaperID_availability_geographical location.</udom>
* paperid: Numerical ID assigned to each research article entered in the matrix that has passed Title/Abstract Review
* speriod: Study Period
    * Indicates specific study period(s) for each study (e.g. P1, P2 …). Although many studies have only one period (data were collected from time period 1 and then time period 2, a study may have multiple study periods if time intervals were not the same for each species included in the study. In this case, enter each distinct time period as a separate line.
* tyear: Total years studied
    * NA: No Data, includes papers that have a date range > 10 years.</edomvd>
    * (End Year-Start Year)+1: If there is a date range in the start and/or end period, use the mid-point of each period to calculate total years studied.  If the author(s) provide median years for the start and end period, then use that instead of calculating as above.  Note: If start date is unclear (e.g. “pre-1970s”) and you cannot calculate total years studied, you should not calculate km/dec shift. Shifts in these cases can be entered qualitatively.
* ntaxa: Number of taxa: Indicate the number of species or distinct population groups assessed in the study.
* sample: Regularity of Sampling: If authors compared ranges at multiple time intervals, indicate how regularly they sampled.
    * NA: If range was only sampled twice
    * irregular: authors sampled ranges periodically throughout study period at irregular time intervals
    * regular: authors sampled ranges continuously throughout study period at specified time intervals, such as every year or more
* nsample: Number of sampling periods
    * NA: No Data
    * Indicate the number of sampling events during the study. If number is unclear we recorded NA
* grain: If quantitative data on range shifts were provided (i.e., shifts reported in a unit of shift over a period of time), indicate the spatial resolution of the data used to generate range shift estimates
    * NA: No quantitative data
    * fine: Data based on GPS coordinates with spatial resolution of less than or equal to 10 km
    * medium: Data resolution used to calculate range shifts is between fine and coarse.
    * coarse: Data based on range maps or atlas grids with spatial resolution greater than 100 km
* resurvey: Similarity of sample sites in the historical and resurveyed periods
    * resurveyed: Resurvey conducted in same general area, but not in same plots or transects
    * opportunistic: Range shifts calculated from paired designs such as permanent plots or data cleaning or resampling procedure carried out to calculate range shifts on a balanced dataset (e.g. resurvey conducted in the same general area but not the same plots and authors made sure number of sampling units in both time periods was identical)
* raw: Raw or modeled: Indicate the level of extrapolation</attrdef>
    * NA: No Data
    * raw: little to no data cleaning, range shifts obtained from pure observations or descriptive statistics
    * modeled: Range shifts obtained from model outputs (i.e. models used to project range beyond survey points, such as species distribution model, occupancy model, etc.)
* temp: Specific temperature variable measured in the study (eg., mean annual temperature, minimum in third quarter, etc.).
    * NA: If temperature is not assessed, put “n/a”
    * See third tab for corresponding list of coded climate variables (A-B)</udom>
* tobsv: Direction of observed temperature change: Indicate how the temperature variable(s) changed
    * NA: No Data
    * mixed: Select mixed if authors report changes in two or more temperature variables and the changes are not consistent.
    * increase: increase in temperature variable
    * decrease: decrease in temperature variable
    * no change: no change in temperature variables
    * unclear: Changes in temperature variables unclear
* precip: Precipitation variable measured: Specific precipitation variable measured in the study.
    * NA: Precipitation is not assessed
    * See third tab for list of precipitation variables
* pobsv: Direction of Observed Precipitation Changed: Indicate direction of change in precipitation variable</attrdef>
    * NA: No Data
    * mixed: Select mixed if authors report changes in two or more precipitation variables and the changes are not consistent.
    * no change: No change in precipitation variable
    * decrease: decrease in precipitation variable
    * increase: Increase in precipitation variable
    * unclear: Change in precipitation unclear
* nonclim</attrlabl>
        <attrdef>Author Assessment of Non-climate Drivers</attrdef>
        <attrdefs>Producer Defined</attrdefs>
        <attrdomv>
          <edom>
            <edomv>NA</edomv>
            <edomvd>Author does not address this topic</edomvd>
            <edomvds>Producer defined</edomvds>
          </edom>
        </attrdomv>
        <attrdomv>
          <udom>If assessed, indicate how the authors describe the role of non climate drivers in explaining observed range shift.</udom>
        </attrdomv>
      </attr>
      <attr>
        <attrlabl>evac</attrlabl>
        <attrdef>Author assessment of Sensitivity or Adaptive Capacity</attrdef>
        <attrdefs>Producer Defined</attrdefs>
        <attrdomv>
          <edom>
            <edomv>NA</edomv>
            <edomvd>Author does not address this topic</edomvd>
            <edomvds>Producer defined</edomvds>
          </edom>
        </attrdomv>
        <attrdomv>
          <udom>If assessed, describe how the authors account for species sensitivity and/or adaptive capacity in explaining observed responses.</udom>
        </attrdomv>
      </attr>
      <attr>
        <attrlabl>studyarea</attrlabl>
        <attrdef>Indicate study area as described by author.</attrdef>
        <attrdefs>Producer Defined</attrdefs>
        <attrdomv>
          <udom>This should be the most specific description available (as low resolution as possible); we will use this to then create a shape file of the study area. If the study includes multiple locations, list them in one cell, and do not separate them into different rows. Indicate under subsp column which location each observation is from.</udom>
        </attrdomv>
      </attr>
      <attr>
        <attrlabl>hem</attrlabl>
        <attrdef>Hemisphere: Indicate which hemisphere the study occurs in</attrdef>
        <attrdefs>Producer Defined</attrdefs>
        <attrdomv>
          <edom>
            <edomv>northern</edomv>
            <edomvd>Northern- northern hemisphere</edomvd>
            <edomvds>Producer defined</edomvds>
          </edom>
        </attrdomv>
        <attrdomv>
          <edom>
            <edomv>southern</edomv>
            <edomvd>Southern- southern hemisphere</edomvd>
            <edomvds>Producer defined</edomvds>
          </edom>
        </attrdomv>
        <attrdomv>
          <edom>
            <edomv>both</edomv>
            <edomvd>Both- both</edomvd>
            <edomvds>Producer defined</edomvds>
          </edom>
        </attrdomv>
      </attr>
      <attr>
        <attrlabl>ecotype</attrlabl>
        <attrdef>Ecosystem: Indicate the general ecosystem</attrdef>
        <attrdefs>Producer Defined</attrdefs>
        <attrdomv>
          <edom>
            <edomv>terrestrial</edomv>
            <edomvd>Terrestrial- terrestrial environment</edomvd>
            <edomvds>Producer defined</edomvds>
          </edom>
        </attrdomv>
        <attrdomv>
          <edom>
            <edomv>marine</edomv>
            <edomvd>Marine- marine environment</edomvd>
            <edomvds>Producer defined</edomvds>
          </edom>
        </attrdomv>
        <attrdomv>
          <edom>
            <edomv>aquatic</edomv>
            <edomvd>Aquatic- aquatic environment</edomvd>
            <edomvds>Producer defined</edomvds>
          </edom>
        </attrdomv>
      </attr>
      <attr>
        <attrlabl>habtype</attrlabl>
        <attrdef>Habitat Type</attrdef>
        <attrdefs>Producer Defined</attrdefs>
        <attrdomv>
          <udom>Indicate the type of habitats studied</udom>
        </attrdomv>
      </attr>
      <attr>
        <attrlabl>sciname</attrlabl>
        <attrdef>Binomial nomenclature of the focal species, consisting of genus name and specific epithet.</attrdef>
        <attrdefs>Producer Defined</attrdefs>
        <attrdomv>
          <udom>Scientific name of focal species</udom>
        </attrdomv>
      </attr>
      <attr>
        <attrlabl>cname</attrlabl>
        <attrdef>Common name of the focal species</attrdef>
        <attrdefs>Producer Defined</attrdefs>
        <attrdomv>
          <udom>Common name of focal species</udom>
        </attrdomv>
      </attr>
      <attr>
        <attrlabl>tax</attrlabl>
        <attrdef>Taxonomic group the focal species belongs to.</attrdef>
        <attrdefs>Producer Defined</attrdefs>
        <attrdomv>
          <edom>
            <edomv>bird</edomv>
            <edomvd>bird</edomvd>
            <edomvds>Producer defined</edomvds>
          </edom>
        </attrdomv>
        <attrdomv>
          <edom>
            <edomv>plant</edomv>
            <edomvd>plant</edomvd>
            <edomvds>Producer defined</edomvds>
          </edom>
        </attrdomv>
        <attrdomv>
          <edom>
            <edomv>fish</edomv>
            <edomvd>fish</edomvd>
            <edomvds>Producer defined</edomvds>
          </edom>
        </attrdomv>
        <attrdomv>
          <edom>
            <edomv>mammal</edomv>
            <edomvd>mammal</edomvd>
            <edomvds>Producer defined</edomvds>
          </edom>
        </attrdomv>
        <attrdomv>
          <edom>
            <edomv>other</edomv>
            <edomvd>other</edomvd>
            <edomvds>Producer defined</edomvds>
          </edom>
        </attrdomv>
        <attrdomv>
          <edom>
            <edomv>insect</edomv>
            <edomvd>insect</edomvd>
            <edomvds>Producer defined</edomvds>
          </edom>
        </attrdomv>
        <attrdomv>
          <edom>
            <edomv>amphibian</edomv>
            <edomvd>amphibian</edomvd>
            <edomvds>Producer defined</edomvds>
          </edom>
        </attrdomv>
        <attrdomv>
          <edom>
            <edomv>reptile</edomv>
            <edomvd>reptile</edomvd>
            <edomvds>Producer defined</edomvds>
          </edom>
        </attrdomv>
      </attr>
      <attr>
        <attrlabl>subsp</attrlabl>
        <attrdef>Subspecies or Population</attrdef>
        <attrdefs>Producer Defined</attrdefs>
        <attrdomv>
          <udom>If data in the paper are reported at a level below species, include the subgroup here. This could be sex of the organism (i.e., range shift data presented separately for males/females); age class (juvenile/adult); or geographic subpopulation

(southern/northern population).</udom>
        </attrdomv>
      </attr>
      <attr>
        <attrlabl>dim</attrlabl>
        <attrdef>Dimension: Describe what kind of range shift the study attempted to assess: latitude,

longitude, elevation, or depth.</attrdef>
        <attrdefs>Producer Defined</attrdefs>
        <attrdomv>
          <edom>
            <edomv>latitude</edomv>
            <edomvd>shift incurred on the latitudinal gradient</edomvd>
            <edomvds>Producer defined</edomvds>
          </edom>
        </attrdomv>
        <attrdomv>
          <edom>
            <edomv>elevation</edomv>
            <edomvd>shift incurred on the elevation gradient</edomvd>
            <edomvds>Producer defined</edomvds>
          </edom>
        </attrdomv>
        <attrdomv>
          <edom>
            <edomv>depth</edomv>
            <edomvd>shift incurred on the depth gradient</edomvd>
            <edomvds>Producer defined</edomvds>
          </edom>
        </attrdomv>
        <attrdomv>
          <edom>
            <edomv>longitude</edomv>
            <edomvd>shift incurred on the longitudinal gradient</edomvd>
            <edomvds>Producer defined</edomvds>
          </edom>
        </attrdomv>
      </attr>
      <attr>
        <attrlabl>obsvt</attrlabl>
        <attrdef>Observation type: Describe whether the observation is of a shift in occupancy; or a shift

in abundance</attrdef>
        <attrdefs>Producer Defined</attrdefs>
        <attrdomv>
          <edom>
            <edomv>occupancy shift</edomv>
            <edomvd>Occupancy shift: a change in where the species is present or absent (e.g. shift in
average latitude or maximum elevation)</edomvd>
            <edomvds>Producer defined</edomvds>
          </edom>
        </attrdomv>
        <attrdomv>
          <edom>
            <edomv>abundance shift</edomv>
            <edomvd>Abundance shift: a change in the distribution of population (e.g. shift in 
optimum/maximum abundance or increase in abundance at the leading edge)</edomvd>
            <edomvds>Producer defined</edomvds>
          </edom>
        </attrdomv>
      </attr>
      <attr>
        <attrlabl>param</attrlabl>
        <attrdef>Parameter: Describe what part or measure of the range the analysis applies to</attrdef>
        <attrdefs>Producer Defined</attrdefs>
        <attrdomv>
          <edom>
            <edomv>leading edge</edomv>
            <edomvd>Leading edge: movement is poleward, upward, or deeper</edomvd>
            <edomvds>Producer defined</edomvds>
          </edom>
        </attrdomv>
        <attrdomv>
          <edom>
            <edomv>mean</edomv>
            <edomvd>Mean: movement at the center of species range</edomvd>
            <edomvds>Producer defined</edomvds>
          </edom>
        </attrdomv>
        <attrdomv>
          <edom>
            <edomv>trailing edge</edomv>
            <edomvd>Trailing edge: movement is equatorial, downslope, shallower</edomvd>
            <edomvds>Producer defined</edomvds>
          </edom>
        </attrdomv>
        <attrdomv>
          <edom>
            <edomv>maximum/optimum</edomv>
            <edomvd>Maximum/Optimum: the point in the range that that has the highest abundance and/or the mean of the range weighted by abundance

East/west</edomvd>
            <edomvds>Producer defined</edomvds>
          </edom>
        </attrdomv>
        <attrdomv>
          <edom>
            <edomv>west</edomv>
            <edomvd>longitudinal shift west of range</edomvd>
            <edomvds>Producer defined</edomvds>
          </edom>
        </attrdomv>
        <attrdomv>
          <edom>
            <edomv>east</edomv>
            <edomvd>longitudinal shift east of range</edomvd>
            <edomvds>Producer defined</edomvds>
          </edom>
        </attrdomv>
      </attr>
      <attr>
        <attrlabl>catchange</attrlabl>
        <attrdef>Categorical change; provide qualitative assessment of the observation</attrdef>
        <attrdefs>Producer Defined</attrdefs>
        <attrdomv>
          <edom>
            <edomv>latitudinal increase</edomv>
            <edomvd>Latitudinal increase: the boundary measurement (e.g., leading edge) increases in latitude</edomvd>
            <edomvds>Producer defined</edomvds>
          </edom>
        </attrdomv>
        <attrdomv>
          <edom>
            <edomv>no change</edomv>
            <edomvd>No change: no change was observed or there was a change reported but it was not

significant</edomvd>
            <edomvds>Producer defined</edomvds>
          </edom>
        </attrdomv>
        <attrdomv>
          <edom>
            <edomv>latitudinal decrease</edomv>
            <edomvd>Latitudinal decrease: the boundary measurement (e.g., leading edge) decreases in latitude</edomvd>
            <edomvds>Producer defined</edomvds>
          </edom>
        </attrdomv>
        <attrdomv>
          <edom>
            <edomv>elevational increase</edomv>
            <edomvd>Elevational increase: the boundary measurement (e.g., leading edge) increases in latitude</edomvd>
            <edomvds>Producer defined</edomvds>
          </edom>
        </attrdomv>
        <attrdomv>
          <edom>
            <edomv>elevational decrease</edomv>
            <edomvd>Elevational decrease: the boundary measurement (e.g., leading edge) decreases in elevation</edomvd>
            <edomvds>Producer defined</edomvds>
          </edom>
        </attrdomv>
        <attrdomv>
          <edom>
            <edomv>depth increase</edomv>
            <edomvd>depth increase: the boundary measurement (e.g., leading edge) increases in depth</edomvd>
            <edomvds>Producer defined</edomvds>
          </edom>
        </attrdomv>
        <attrdomv>
          <edom>
            <edomv>depth decrease</edomv>
            <edomvd>Depth decrease: the boundary measurement (e.g., leading edge) decreases in depth</edomvd>
            <edomvds>Producer defined</edomvds>
          </edom>
        </attrdomv>
        <attrdomv>
          <edom>
            <edomv>longitudinal shift</edomv>
            <edomvd>Longitudinal shift: a change in longitude (either east or west): west should be recorded as negative numbers, east is recorded as positive numbers

Etc</edomvd>
            <edomvds>Producer defined</edomvds>
          </edom>
        </attrdomv>
        <attrdomv>
          <edom>
            <edomv>abundance decrease</edomv>
            <edomvd>Abundance measures decreased</edomvd>
            <edomvds>Producer defined</edomvds>
          </edom>
        </attrdomv>
        <attrdomv>
          <edom>
            <edomv>abundance increase</edomv>
            <edomvd>Abundance measures increased</edomvd>
            <edomvds>Producer defined</edomvds>
          </edom>
        </attrdomv>
      </attr>
      <attr>
        <attrlabl>nchange</attrlabl>
        <attrdef>Numeric Change. If available, describe the quantitative change</attrdef>
        <attrdefs>Producer Defined</attrdefs>
        <attrdomv>
          <edom>
            <edomv>NA</edomv>
            <edomvd>No Data</edomvd>
            <edomvds>Producer defined</edomvds>
          </edom>
        </attrdomv>
        <attrdomv>
          <rdom>
            <rdommin>-401000.0</rdommin>
            <rdommax>854000.0</rdommax>
          </rdom>
        </attrdomv>
      </attr>
      <attr>
        <attrlabl>unit</attrlabl>
        <attrdef>Metric/Unit: Describe the associated metric (e.g., km/year, total meters change, degree latitude, etc.)</attrdef>
        <attrdefs>Producer Defined</attrdefs>
        <attrdomv>
          <edom>
            <edomv>NA</edomv>
            <edomvd>No Data</edomvd>
            <edomvds>Producer defined</edomvds>
          </edom>
        </attrdomv>
        <attrdomv>
          <edom>
            <edomv>degrees lat/year</edomv>
            <edomvd>Degrees of geographic latitude per year</edomvd>
            <edomvds>Producer defined</edomvds>
          </edom>
        </attrdomv>
        <attrdomv>
          <edom>
            <edomv>m</edomv>
            <edomvd>meters</edomvd>
            <edomvds>Producer defined</edomvds>
          </edom>
        </attrdomv>
        <attrdomv>
          <edom>
            <edomv>km</edomv>
            <edomvd>kilometers</edomvd>
            <edomvds>Producer defined</edomvds>
          </edom>
        </attrdomv>
        <attrdomv>
          <edom>
            <edomv>m/decade</edomv>
            <edomvd>meters per decade</edomvd>
            <edomvds>Producer defined</edomvds>
          </edom>
        </attrdomv>
        <attrdomv>
          <edom>
            <edomv>m/year</edomv>
            <edomvd>meters per year</edomvd>
            <edomvds>Producer defined</edomvds>
          </edom>
        </attrdomv>
        <attrdomv>
          <edom>
            <edomv>km/year</edomv>
            <edomvd>kilometers per year</edomvd>
            <edomvds>Producer defined</edomvds>
          </edom>
        </attrdomv>
        <attrdomv>
          <edom>
            <edomv>degrees lat</edomv>
            <edomvd>Latitudinal degrees</edomvd>
            <edomvds>Producer defined</edomvds>
          </edom>
        </attrdomv>
        <attrdomv>
          <edom>
            <edomv>ft</edomv>
            <edomvd>feet</edomvd>
            <edomvds>Producer defined</edomvds>
          </edom>
        </attrdomv>
        <attrdomv>
          <edom>
            <edomv>degrees longitude</edomv>
            <edomvd>longitudinal degrees</edomvd>
            <edomvds>Producer defined</edomvds>
          </edom>
        </attrdomv>
        <attrdomv>
          <edom>
            <edomv>km/decade</edomv>
            <edomvd>kilometers per decade</edomvd>
            <edomvds>Producer defined</edomvds>
          </edom>
        </attrdomv>
        <attrdomv>
          <edom>
            <edomv>degree longitude/year</edomv>
            <edomvd>degrees of longitude per year</edomvd>
            <edomvds>Producer defined</edomvds>
          </edom>
        </attrdomv>
        <attrdomv>
          <edom>
            <edomv>degree latitude per decade</edomv>
            <edomvd>degrees of latitude per decade</edomvd>
            <edomvds>Producer defined</edomvds>
          </edom>
        </attrdomv>
      </attr>
      <attr>
        <attrlabl>fig.y</attrlabl>
        <attrdef>Found in table/page</attrdef>
        <attrdefs>Producer Defined</attrdefs>
        <attrdomv>
          <udom>Where range shift data were reported in the paper (e.g page number, table, figure)</udom>
        </attrdomv>
      </attr>
      <attr>
        <attrlabl>kmdec</attrlabl>
        <attrdef>Conversion to km/decade: use numeric change and metric data to convert quantitative change to km/decade equivalent.</attrdef>
        <attrdefs>Producer Defined</attrdefs>
        <attrdomv>
          <edom>
            <edomv>NA</edomv>
            <edomvd>No Data</edomvd>
            <edomvds>Producer defined</edomvds>
          </edom>
        </attrdomv>
        <attrdomv>
          <rdom>
            <rdommin>-407.237244</rdommin>
            <rdommax>432.3157895</rdommax>
          </rdom>
        </attrdomv>
      </attr>
      <attr>
        <attrlabl>tsupport</attrlabl>
        <attrdef>Comparison to Historical Variability: Was the observed change significant, based on historical variability in species range?</attrdef>
        <attrdefs>Producer Defined</attrdefs>
        <attrdomv>
          <edom>
            <edomv>supports</edomv>
            <edomvd>Poleward, upslope, and deeper movements support temperature hypotheses.</edomvd>
            <edomvds>Producer defined</edomvds>
          </edom>
        </attrdomv>
        <attrdomv>
          <edom>
            <edomv>fails to support: no change</edomv>
            <edomvd>There was no change</edomvd>
            <edomvds>Producer defined</edomvds>
          </edom>
        </attrdomv>
        <attrdomv>
          <edom>
            <edomv>fails to support</edomv>
            <edomvd>Equatorial, downslope, and shallower movements fail to support</edomvd>
            <edomvds>Producer defined</edomvds>
          </edom>
        </attrdomv>
        <attrdomv>
          <edom>
            <edomv>unclear</edomv>
            <edomvd>If the observed response was unclear</edomvd>
            <edomvds>Producer defined</edomvds>
          </edom>
        </attrdomv>
        <attrdomv>
          <edom>
            <edomv>not assessed</edomv>
            <edomvd>If a temperature hypothesis was not assessed</edomvd>
            <edomvds>Producer defined</edomvds>
          </edom>
        </attrdomv>
      </attr>
      <attr>
        <attrlabl>psupport</attrlabl>
        <attrdef>Supports Precipitation Hypothesis: Assess qualitatively whether the observation

supports, fails to support, or does not address our overarching precipitation hypotheses.</attrdef>
        <attrdefs>Producer Defined</attrdefs>
        <attrdomv>
          <edom>
            <edomv>not assessed</edomv>
            <edomvd>precipitation hypotheses not assessed</edomvd>
            <edomvds>Producer defined</edomvds>
          </edom>
        </attrdomv>
        <attrdomv>
          <edom>
            <edomv>supports</edomv>
            <edomvd>precipitation hypotheses were supported</edomvd>
            <edomvds>Producer defined</edomvds>
          </edom>
        </attrdomv>
        <attrdomv>
          <edom>
            <edomv>unclear</edomv>
            <edomvd>The observations were unclear</edomvd>
            <edomvds>Producer defined</edomvds>
          </edom>
        </attrdomv>
        <attrdomv>
          <edom>
            <edomv>fails to support: no change</edomv>
            <edomvd>No change in observed response</edomvd>
            <edomvds>Producer defined</edomvds>
          </edom>
        </attrdomv>
        <attrdomv>
          <edom>
            <edomv>fails to support</edomv>
            <edomvd>precipitation hypotheses were not supported</edomvd>
            <edomvds>Producer defined</edomvds>
          </edom>
        </attrdomv>
      </attr>
      <attr>
        <attrlabl>notes</attrlabl>
        <attrdef>Notes on study</attrdef>
        <attrdefs>Producer Defined</attrdefs>
        <attrdomv>
          <edom>
            <edomv>&lt;&lt; empty cell &gt;&gt;</edomv>
            <edomvd>No Data</edomvd>
            <edomvds>Producer defined</edomvds>
          </edom>
        </attrdomv>
        <attrdomv>
          <udom>Any notes required to further understand previous columns; to provide context for the paper as a whole across multiple lines of the spreadsheet; or to note any unclear component of the paper.</udom>
        </attrdomv>
      </attr>
      <attr>
        <attrlabl>syear</attrlabl>
        <attrdef>Start year</attrdef>
        <attrdefs>Producer Defined</attrdefs>
        <attrdomv>
          <edom>
            <edomv>NA</edomv>
            <edomvd>No Data</edomvd>
            <edomvds>Producer defined</edomvds>
          </edom>
        </attrdomv>
        <attrdomv>
          <udom>The first year of the study period</udom>
        </attrdomv>
      </attr>
      <attr>
        <attrlabl>eyear</attrlabl>
        <attrdef>End year</attrdef>
        <attrdefs>Producer Defined</attrdefs>
        <attrdomv>
          <edom>
            <edomv>NA</edomv>
            <edomvd>No Data</edomvd>
            <edomvds>Producer defined</edomvds>
          </edom>
        </attrdomv>
        <attrdomv>
          <udom>The last year of the study period</udom>
        </attrdomv>
      </attr>
      <attr>
        <attrlabl>kingdom</attrlabl>
        <attrdef>The taxonomic kingdom the focal species belongs to, refers to taxonomic rank.</attrdef>
        <attrdefs>Producer Defined</attrdefs>
        <attrdomv>
          <edom>
            <edomv>Metazoa</edomv>
            <edomvd>Multicellular, eukaryotic organisms in the Kingdom Animalia.</edomvd>
            <edomvds>Producer defined</edomvds>
          </edom>
        </attrdomv>
        <attrdomv>
          <edom>
            <edomv>Viridiplantae</edomv>
            <edomvd>a clade of eukaryotic organisms that are comprised of green algae, which are primarily aquatic, and land plants.</edomvd>
            <edomvds>Producer defined</edomvds>
          </edom>
        </attrdomv>
        <attrdomv>
          <edom>
            <edomv>Animalia</edomv>
            <edomvd>Multicellular, eukaryotic organisms in the Kingdom Animalia.</edomvd>
            <edomvds>Producer defined</edomvds>
          </edom>
        </attrdomv>
        <attrdomv>
          <edom>
            <edomv>Plantae</edomv>
            <edomvd>photosynthetic eukaryotes that form the kingdom Plantae</edomvd>
            <edomvds>Producer defined</edomvds>
          </edom>
        </attrdomv>
        <attrdomv>
          <edom>
            <edomv>Fungi</edomv>
            <edomvd>any member of the group of eukaryotic organisms that includes yeast, molds, and mushrooms</edomvd>
            <edomvds>Producer defined</edomvds>
          </edom>
        </attrdomv>
      </attr>
      <attr>
        <attrlabl>phylum</attrlabl>
        <attrdef>The taxonomic phylum the focal species belongs to, refers to taxonomic rank.</attrdef>
        <attrdefs>Producer Defined</attrdefs>
        <attrdomv>
          <edom>
            <edomv>Chordata</edomv>
            <edomvd>animals belonging to the phylum Chordata. Chordates at some point in their life cycle possess five primary physical characteristics that distinguish them: a notochord, dorsal hollow nerve cord, endostyle, or thyroid pharyngeal slits, and a post-anal tail.</edomvd>
            <edomvds>Producer defined</edomvds>
          </edom>
        </attrdomv>
        <attrdomv>
          <edom>
            <edomv>Streptophyta</edomv>
            <edomvd>A clade of plants that includes all land plants and green algae, except Chlorophyta and Prasinodermophyta.</edomvd>
            <edomvds>Wikipedia</edomvds>
          </edom>
        </attrdomv>
        <attrdomv>
          <edom>
            <edomv>Tracheophyta</edomv>
            <edomvd>A large group of land plants called vascular plants.</edomvd>
            <edomvds>Producer defined</edomvds>
          </edom>
        </attrdomv>
        <attrdomv>
          <edom>
            <edomv>Arthropoda</edomv>
            <edomvd>invertebrate animals that possess an exoskeleton, segmented body, and paired jointed appendages.</edomvd>
            <edomvds>Producer defined</edomvds>
          </edom>
        </attrdomv>
        <attrdomv>
          <edom>
            <edomv>Cnidaria</edomv>
            <edomvd>Phylum within Kingdom animalia containing aquatic animals found in both freshwater and marine environments</edomvd>
            <edomvds>Wikipedia</edomvds>
          </edom>
        </attrdomv>
        <attrdomv>
          <edom>
            <edomv>Mollusca</edomv>
            <edomvd>Phylum of invertebrate animals known as molluscs or mollusks</edomvd>
            <edomvds>Wikipedia</edomvds>
          </edom>
        </attrdomv>
        <attrdomv>
          <edom>
            <edomv>Annelida</edomv>
            <edomvd>Large phylum of segmented worms that include ragworms, earthworms, and leeches.</edomvd>
            <edomvds>Wikipedia</edomvds>
          </edom>
        </attrdomv>
        <attrdomv>
          <edom>
            <edomv>Echinodermata</edomv>
            <edomvd>Animals known as echinoderms which are recognizable by their adult radial symmetry (e.g. starfish, sea urchins, sand dollars, etc.)</edomvd>
            <edomvds>Wikipedia</edomvds>
          </edom>
        </attrdomv>
        <attrdomv>
          <edom>
            <edomv>Marchantiophyta</edomv>
            <edomvd>a division of non-vascular land plants commonly referred to as hepatics or liverworts</edomvd>
            <edomvds>wikipedia</edomvds>
          </edom>
        </attrdomv>
        <attrdomv>
          <edom>
            <edomv>Bryophyta</edomv>
            <edomvd>A taxonomic division of non-vascular flowerless plants comprised of liverworts, mosses, and hornworts</edomvd>
            <edomvds>wikipedia</edomvds>
          </edom>
        </attrdomv>
        <attrdomv>
          <edom>
            <edomv>Chytridiomycota</edomv>
            <edomvd>A division of zoosporic organism in the kingdom Fungi, informally known as chytrids</edomvd>
            <edomvds>Wikipedia</edomvds>
          </edom>
        </attrdomv>
        <attrdomv>
          <edom>
            <edomv>Ascomycota</edomv>
            <edomvd>a Phylum in the Fungi kingdom that includes sac fungi</edomvd>
            <edomvds>wikipedia</edomvds>
          </edom>
        </attrdomv>
      </attr>
      <attr>
        <attrlabl>class</attrlabl>
        <attrdef>The taxonomic class the focal species belongs to, refers to taxonomic rank.</attrdef>
        <attrdefs>Producer Defined</attrdefs>
        <attrdomv>
          <udom>identify the class that the focal species is from</udom>
        </attrdomv>
      </attr>
      <attr>
        <attrlabl>order</attrlabl>
        <attrdef>The taxonomic order the focal species belongs to, refers to taxonomic rank.</attrdef>
        <attrdefs>Producer Defined</attrdefs>
        <attrdomv>
          <edom>
            <edomv>NA</edomv>
            <edomvd>No Data</edomvd>
            <edomvds>Producer defined</edomvds>
          </edom>
        </attrdomv>
        <attrdomv>
          <udom>identify the order that the focal species is from</udom>
        </attrdomv>
      </attr>
      <attr>
        <attrlabl>family</attrlabl>
        <attrdef>The taxonomic family the focal species belongs to, refers to taxonomic rank.</attrdef>
        <attrdefs>Producer Defined</attrdefs>
        <attrdomv>
          <edom>
            <edomv>NA</edomv>
            <edomvd>No Data</edomvd>
            <edomvds>Producer defined</edomvds>
          </edom>
        </attrdomv>
        <attrdomv>
          <udom>identify the famiy that the focal species is from</udom>
        </attrdomv>
      </attr>
      <attr>
        <attrlabl>genus</attrlabl>
        <attrdef>The taxonomic genus the focal species belongs to, refers to taxonomic rank.</attrdef>
        <attrdefs>Producer Defined</attrdefs>
        <attrdomv>
          <edom>
            <edomv>NA</edomv>
            <edomvd>No Data</edomvd>
            <edomvds>Producer defined</edomvds>
          </edom>
        </attrdomv>
        <attrdomv>
          <udom>identify the genus that the focal species is from</udom>
        </attrdomv>
      </attr>
      <attr>
        <attrlabl>species</attrlabl>
        <attrdef>The taxonomic species the focal species belongs to, refers to taxonomic rank.</attrdef>
        <attrdefs>Producer Defined</attrdefs>
        <attrdomv>
          <udom>identify the species that the focal species is from</udom>
        </attrdomv>
      </attr>
      <attr>
        <attrlabl>data_source_title</attrlabl>
        <attrdef>Source of taxonomic data</attrdef>
        <attrdefs>Producer Defined</attrdefs>
        <attrdomv>
          <edom>
            <edomv>NCBI</edomv>
            <edomvd>National Center for Biotechnology Information (NCBI). Natl. Libr. Med. 
(US), Natl. Cent. Biotechnol. Inf. https://www.ncbi.nlm.nih.gov/</edomvd>
            <edomvds>Producer defined</edomvds>
          </edom>
        </attrdomv>
        <attrdomv>
          <edom>
            <edomv>GBIF Backbone Taxonomy</edomv>
            <edomvd>GBIF Secretariat. GBIF Backbone Taxonomy. https://doi.org/10.15468/
39omei.</edomvd>
            <edomvds>Producer defined</edomvds>
          </edom>
        </attrdomv>
        <attrdomv>
          <edom>
            <edomv>Arctos</edomv>
            <edomvd>Arctos. https://arctos.database.museum/home.cfm.</edomvd>
            <edomvds>Producer defined</edomvds>
          </edom>
        </attrdomv>
        <attrdomv>
          <edom>
            <edomv>GBIF</edomv>
            <edomvd>Global Biodiversity Information Facility. https://www.gbif.org/</edomvd>
            <edomvds>Producer defined</edomvds>
          </edom>
        </attrdomv>
        <attrdomv>
          <edom>
            <edomv>iNaturalist</edomv>
            <edomvd>iNaturalist. https://www.inaturalist.org.</edomvd>
            <edomvds>Producer defined</edomvds>
          </edom>
        </attrdomv>
        <attrdomv>
          <edom>
            <edomv>manual</edomv>
            <edomvd>Searched manually</edomvd>
            <edomvds>Producer defined</edomvds>
          </edom>
        </attrdomv>
      </attr>
      <attr>
        <attrlabl>k2</attrlabl>
        <attrdef>New kingdom classification used for analysis</attrdef>
        <attrdefs>Producer defined</attrdefs>
        <attrdomv>
          <edom>
            <edomv>Animalia</edomv>
            <edomvd>Multicellular, eukaryotic organisms in the Kingdom Animalia.</edomvd>
            <edomvds>Producer defined</edomvds>
          </edom>
        </attrdomv>
        <attrdomv>
          <edom>
            <edomv>Plantae</edomv>
            <edomvd>photosynthetic eukaryotes that form the kingdom Plantae</edomvd>
            <edomvds>Producer defined</edomvds>
          </edom>
        </attrdomv>
      </attr>
      <attr>
        <attrlabl>t2</attrlabl>
        <attrdef>New taxa group used for analysis</attrdef>
        <attrdefs>Producer Defined</attrdefs>
        <attrdomv>
          <udom>Following taxonomic harmonization, we grouped some classes into higher order groups for analysis (e.g., mollusks, crustaceans, plants)</udom>
        </attrdomv>
      </attr>
      <attr>
        <attrlabl>casc</attrlabl>
        <attrdef>USGS casc region. If study fell within several boundaries, they are separated by a semicolon (;)</attrdef>
        <attrdefs>Producer Defined</attrdefs>
        <attrdomv>
          <edom>
            <edomv>NA</edomv>
            <edomvd>Not applicable, study did not fall within a CASC boundary</edomvd>
            <edomvds>Producer defined</edomvds>
          </edom>
        </attrdomv>
        <attrdomv>
          <edom>
            <edomv>Alaska</edomv>
            <edomvd>Geography spans the state of Alaska</edomvd>
            <edomvds>Producer defined</edomvds>
          </edom>
        </attrdomv>
        <attrdomv>
          <edom>
            <edomv>Contiguous United States</edomv>
            <edomvd>
            </edomvd>
            <edomvds>Producer defined</edomvds>
          </edom>
        </attrdomv>
        <attrdomv>
          <edom>
            <edomv>North Central</edomv>
            <edomvd>Geography spans Montana, Wyoming, Colorado, North Dakota, South Dakota, Nebraska, and Kansas.</edomvd>
            <edomvds>Producer defined</edomvds>
          </edom>
        </attrdomv>
        <attrdomv>
          <edom>
            <edomv>Northeast</edomv>
            <edomvd>Geography includes the states of Connecticut, Delaware, Kentucky, Maine, Maryland, Massachusetts, New Hampshire, New Jersey, New York, Pennsylvania, Rhode Island, Virginia, Vermont, and West Virginia.</edomvd>
            <edomvds>Producer defined</edomvds>
          </edom>
        </attrdomv>
        <attrdomv>
          <edom>
            <edomv>Northwest</edomv>
            <edomvd>Geography spans Washington, Oregon, and Idaho.</edomvd>
            <edomvds>Producer defined</edomvds>
          </edom>
        </attrdomv>
        <attrdomv>
          <edom>
            <edomv>South Central</edomv>
            <edomvd>Geography spans Oklahoma, Texas, Louisiana, and New Mexico.</edomvd>
            <edomvds>Producer defined</edomvds>
          </edom>
        </attrdomv>
        <attrdomv>
          <edom>
            <edomv>Southeast</edomv>
            <edomvd>Geography spans North Carolina, South Carolina, Georgia, Alabama, Mississippi, Florida, Tennessee, Arkansas, Puerto Rico, and the U.S. Virgin Islands</edomvd>
            <edomvds>Producer defined</edomvds>
          </edom>
        </attrdomv>
        <attrdomv>
          <edom>
            <edomv>Southwest</edomv>
            <edomvd>Geography spans Arizona, Utah, California, and Nevada.</edomvd>
            <edomvds>Producer defined</edomvds>
          </edom>
        </attrdomv>
        <attrdomv>
          <edom>
            <edomv>Pacific Islands</edomv>
            <edomvd>Geography spans  American Samoa, the Commonwealth of the Northern Mariana Islands, the Federated States of Micronesia, Guam, Hawai'i, Palau, and the Republic of the Marshall Islands.</edomvd>
            <edomvds>Producer defined</edomvds>
          </edom>
        </attrdomv>
      </attr>
    </detailed>
    <detailed>
      <enttyp>
        <enttypl>PaperID.csv</enttypl>
        <enttypd>Comma Separated Value (CSV) file containing data.</enttypd>
        <enttypds>Producer Defined</enttypds>
      </enttyp>
      <attr>
        <attrlabl>Paper ID</attrlabl>
        <attrdef>Numerical Identifier given to each article that passed title/abstract review</attrdef>
        <attrdefs>Producer Defined</attrdefs>
        <attrdomv>
          <rdom>
            <rdommin>1</rdommin>
            <rdommax>842</rdommax>
          </rdom>
        </attrdomv>
      </attr>
      <attr>
        <attrlabl>Author</attrlabl>
        <attrdef>Abbreviated authors of the article</attrdef>
        <attrdefs>Producer Defined</attrdefs>
        <attrdomv>
          <udom>Here we noted the authors of each article in abbreviated form.</udom>
        </attrdomv>
      </attr>
      <attr>
        <attrlabl>Title</attrlabl>
        <attrdef>Title of the article</attrdef>
        <attrdefs>Producer Defined</attrdefs>
        <attrdomv>
          <udom>Full title of the article</udom>
        </attrdomv>
      </attr>
      <attr>
        <attrlabl>Year</attrlabl>
        <attrdef>Year of publication</attrdef>
        <attrdefs>Producer Defined</attrdefs>
        <attrdomv>
          <udom>The year the article was published</udom>
        </attrdomv>
      </attr>
      <attr>
        <attrlabl>Journal</attrlabl>
        <attrdef>The journal publication</attrdef>
        <attrdefs>Producer Defined</attrdefs>
        <attrdomv>
          <udom>The journal or book that the article was published in</udom>
        </attrdomv>
      </attr>
      <attr>
        <attrlabl>DOI</attrlabl>
        <attrdef>Digitial Object Identifier (DOI), or persistent identifier to uniquely identify each article, assigned by the article publisher.</attrdef>
        <attrdefs>Producer Defined</attrdefs>
        <attrdomv>
          <edom>
            <edomv>n/a</edomv>
            <edomvd>No Data</edomvd>
            <edomvds>Producer defined</edomvds>
          </edom>
        </attrdomv>
        <attrdomv>
          <udom>The DOI for each article, if available</udom>
        </attrdomv>
      </attr>
    </detailed>
    <detailed>
      <enttyp>
        <enttypl>Climate.Variables.csv</enttypl>
        <enttypd>Comma Separated Value (CSV) file containing data.</enttypd>
        <enttypds>Producer Defined</enttypds>
      </enttyp>
      <attr>
        <attrlabl>Reference Number</attrlabl>
        <attrdef>The letter/number combination assigned to each climate variable</attrdef>
        <attrdefs>Producer Defined</attrdefs>
        <attrdomv>
          <udom>Each variable was assigned a reference code. A codes refer to temperature variables. B codes refer to water temperature variables. C codes refer to precipitation variables.</udom>
        </attrdomv>
      </attr>
      <attr>
        <attrlabl>Variable Description</attrlabl>
        <attrdef>Description of the climate variable</attrdef>
        <attrdefs>Producer Defined</attrdefs>
        <attrdomv>
          <udom>The climate variable that corresponds to the reference number.</udom>
        </attrdomv>
      </attr>
    </detailed>
    <detailed>
      <enttyp>
        <enttypl>studyarea.shapefiles.shp</enttypl>
        <enttypd>Table containing attribute information associated with the data set.</enttypd>
        <enttypds>Producer Defined</enttypds>
      </enttyp>
      <attr>
        <attrlabl>FID</attrlabl>
        <attrdef>Internal feature number.</attrdef>
        <attrdefs>ESRI</attrdefs>
        <attrdomv>
          <udom>Sequential unique whole numbers that are automatically generated.</udom>
        </attrdomv>
      </attr>
      <attr>
        <attrlabl>Shape</attrlabl>
        <attrdef>Feature geometry.</attrdef>
        <attrdefs>ESRI</attrdefs>
        <attrdomv>
          <udom>Shape type.</udom>
        </attrdomv>
      </attr>
      <attr>
        <attrlabl>Name</attrlabl>
        <attrdef>Name of Polygon</attrdef>
        <attrdefs>Producer Defined</attrdefs>
        <attrdomv>
          <udom>Name of Polygon</udom>
        </attrdomv>
      </attr>
      <attr>
        <attrlabl>paperid</attrlabl>
        <attrdef>Numerical ID assigned to each research article entered in the matrix that has passed Title/Abstract Review</attrdef>
        <attrdefs>Producer Defined</attrdefs>
        <attrdomv>
          <rdom>
            <rdommin>1</rdommin>
            <rdommax>842</rdommax>
          </rdom>
        </attrdomv>
      </attr>
      <attr>
        <attrlabl>avlblty</attrlabl>
        <attrdef>Spatial scale of the polygon (availability)</attrdef>
        <attrdefs>Producer Defined</attrdefs>
        <attrdomv>
          <edom>
            <edomv>STUDY-LEVEL</edomv>
            <edomvd>Spatial data available at the study level. Referenced in polygon naming convention as 'SL'</edomvd>
            <edomvds>Producer defined</edomvds>
          </edom>
        </attrdomv>
        <attrdomv>
          <edom>
            <edomv>SPP-LEVEL</edomv>
            <edomvd>Spatial data available at the species level. Referenced in polygon naming convention as 'SPL'</edomvd>
            <edomvds>Producer defined</edomvds>
          </edom>
        </attrdomv>
        <attrdomv>
          <edom>
            <edomv>POP-LEVEL</edomv>
            <edomvd>Spatial data available for distinct populations. Referenced in polygon naming convention as 'POPLVL'</edomvd>
            <edomvds>Producer defined</edomvds>
          </edom>
        </attrdomv>
      </attr>
      <attr>
        <attrlabl>quality</attrlabl>
        <attrdef>How to obtain spatial data</attrdef>
        <attrdefs>Producer Defined</attrdefs>
        <attrdomv>
          <edom>
            <edomv>DIG</edomv>
            <edomvd>No supplementary data, spatial extent for a given level must be approximately hand-digitized in Google Earth based solely on descriptions of the study area available in the article or associated research organization website</edomvd>
            <edomvds>Producer defined</edomvds>
          </edom>
        </attrdomv>
        <attrdomv>
          <edom>
            <edomv>FIGDIG</edomv>
            <edomvd>Spatial info cannot be extracted directly from relevant figure, but relevant figure can assist in hand-digitization</edomvd>
            <edomvds>Producer defined</edomvds>
          </edom>
        </attrdomv>
        <attrdomv>
          <edom>
            <edomv>DIGI</edomv>
            <edomvd>No supplementary data, spatial info can be extracted from a relevant figure(s)</edomvd>
            <edomvds>Producer defined</edomvds>
          </edom>
        </attrdomv>
      </attr>
      <attr>
        <attrlabl>access</attrlabl>
        <attrdef>Where to find the data used to generate the polygon</attrdef>
        <attrdefs>Producer Defined</attrdefs>
        <attrdomv>
          <udom>Contains relevant links for supplementary data access,  relevant figure(s), relevant study area description(s) from text</udom>
        </attrdomv>
      </attr>
      <attr>
        <attrlabl>sptlnts</attrlabl>
        <attrdef>Any notes on the spatial information relevant to the study.</attrdef>
        <attrdefs>Producer Defined</attrdefs>
        <attrdomv>
          <edom>
            <edomv>&lt;&lt; empty cell &gt;&gt;</edomv>
            <edomvd>No Data</edomvd>
            <edomvds>Producer defined</edomvds>
          </edom>
        </attrdomv>
        <attrdomv>
          <udom>Qualitative description that may be useful for future users of the spatial data.</udom>
        </attrdomv>
      </attr>
    </detailed>
    <overview>
      <eaover>The database has three related components. The first component, Paper ID, contains citation information for each article used in our study. The second component, Study Species Data, contains the relevant information retrieved from the articles about the study design, location, time period, species information, and data on the range shifts. The final component is a key to understanding the climate variables used in the study species data tab.</eaover>
      <eadetcit>Madeleine A. Rubenstein, Sarah R. Weiskopf; Romain Bertrand, Shawn L. Carter, Lise Comte, Mitchell J. Eaton, Ciara G. Johnson, Jonathan Lenoir, Abigail J. Lynch, Daria Yurevna Maslyukova, Brian W. Miller, Toni Lyn Morelli, Evan J. Parker, Christopher Poole, Mari Angel Rodriguez, Theresa Rudick, Adam Terando, Laura M. Thompson, Keanah Turner. (2023). CoRE (Contractions or Range Expansions) Database [database]. Retrieved from https://doi.org/10.5066/P99VP2TW</eadetcit>
    </overview>
  </eainfo>
  <distinfo>
    <distrib>
      <cntinfo>
        <cntperp>
          <cntper>GS ScienceBase</cntper>
          <cntorg>U.S. Geological Survey</cntorg>
        </cntperp>
        <cntaddr>
          <addrtype>mailing address</addrtype>
          <address>Denver Federal Center, Building 810, Mail Stop 302</address>
          <city>Denver</city>
          <state>CO</state>
          <postal>80225</postal>
          <country>United States</country>
        </cntaddr>
        <cntvoice>1-888-275-8747</cntvoice>
        <cntemail>sciencebase@usgs.gov</cntemail>
      </cntinfo>
    </distrib>
    <distliab>Unless otherwise stated, all data, metadata and related materials are considered to satisfy the quality standards relative to the purpose for which the data were collected. Although these data and associated metadata have been reviewed for accuracy and completeness and approved for release by the U.S. Geological Survey (USGS), no warranty expressed or implied is made regarding the display or utility of the data for other purposes, nor on all computer systems, nor shall the act of distribution constitute any such warranty.</distliab>
    <stdorder>
      <digform>
        <digtinfo>
          <formname>Digital Data</formname>
        </digtinfo>
        <digtopt>
          <onlinopt>
            <computer>
              <networka>
                <networkr>https://doi.org/10.5066/P99VP2TW</networkr>
              </networka>
            </computer>
          </onlinopt>
        </digtopt>
      </digform>
      <fees>None</fees>
    </stdorder>
  </distinfo>
  <metainfo>
    <metd>20240529</metd>
    <metc>
      <cntinfo>
        <cntperp>
          <cntper>Sarah R Weiskopf</cntper>
          <cntorg>U.S. Geological Survey, ECOSYSTEMS</cntorg>
        </cntperp>
        <cntpos>NCASC National Biodiversity Lead</cntpos>
        <cntaddr>
          <addrtype>mailing address</addrtype>
          <address>12201 Sunrise Valley Dr</address>
          <city>Reston</city>
          <state>VA</state>
          <postal>20192</postal>
          <country>US</country>
        </cntaddr>
        <cntvoice>703-648-4073</cntvoice>
        <cntemail>sweiskopf@usgs.gov</cntemail>
      </cntinfo>
    </metc>
    <metstdn>FGDC Biological Data Profile of the Content Standard for Digital Geospatial Metadata</metstdn>
    <metstdv>FGDC-STD-001.1-1999</metstdv>
  </metainfo>
</metadata>
